#!/bin/bash

echo "Creating menu button..."
mkdir -p ~/.local/share/applications
echo "[Desktop Entry]
Name=Simple To-Do List
Comment=A Simple To-Do List
Exec=/home/pi/ToDoList/start
Icon=/home/pi/ToDoList/icons/todo.jpeg
Terminal=false
Type=Application
Categories=Utility;" > ~/.local/share/applications/To-Do.desktop