#!/bin/bash

echo "This app was made by AlienGames™"

sleep 1

echo "my youtube channel is https://www.youtube.com/channel/UC1BmibJN5Eq3jQVLA1AfEMg?"

sleep 1

echo "Please wait while Simple To-Do List Starts"

sleep 1

spinner() {
    local i sp n
    sp='/~\|'
    n=${#sp}
    printf ''
    while sleep 0.1; do
        printf "%s\b" "${sp:i++%n:1}"
    done
}

printf 'Starting!'
spinner &

sleep 6  

kill "$!" # kill the spinner
echo "  (done!)"

sleep 1

spinner() {
    local i sp n
    sp='/~\|'
    n=${#sp}
    printf ' '
    while sleep 0.1; do
        printf "%s\b" "${sp:i++%n:1}"
    done
}

printf 'Adding Labels!'
spinner &

sleep 6  

kill "$!" # kill the spinner
echo "  (done!)"

sleep 1

spinner() {
    local i sp n
    sp='/~\|'
    n=${#sp}
    printf ''
    while sleep 0.1; do
        printf "%s\b" "${sp:i++%n:1}"
    done
}

printf 'Adding Text-Boxes!'
spinner &

sleep 6  

kill "$!" # kill the spinner
echo "  (done!)"

sleep 1

spinner() {
    local i sp n
    sp='/~\|'
    n=${#sp}
    printf ''
    while sleep 0.1; do
        printf "%s\b" "${sp:i++%n:1}"
    done
}

printf 'Adding Buttons!'
spinner &

sleep 6  

kill "$!" # kill the spinner
echo "  (done!)"

sleep 1

echo "Simple To-Do list started!"

sleep 1

echo "Close Terminal or inside the app to close out the app"

sleep 1

sudo python3 ${HOME}/ToDoList/src/ToDoList.py ${HOME} > ToDoList.log
